### ISSUE TITLE
No connection can be made to the deployed application

### ISSUE THREAD

**Issue by uskudarli** [koray-bostanci/SWE573#35]
The following address is not reachable.

http://54.91.163.71/core/index/

**Comment by koray-bostanci** [comment]
Hi @uskudarli ,

Could you please use the following address.

http://34.194.188.217:8000/core/index/ 

I had to change my url due to a key error in my server.  I've updated the url in piazza but may be it's not seen. Sorry for the inconvenience.

![image](https://cloud.githubusercontent.com/assets/8762343/21605833/b5558ac6-d1bc-11e6-849d-410349c1dd28.png)
